### PR TITLE
Add model for Latin enclitic splitter

### PR DESCRIPTION
**Pull request by diyclassics**
Adds the enclitic splitter model needed for the refactoried Latin tokenizer

### CODE REVIEW

**Comment by kylepjohnson** [comment]
1) Could you put here some code to test this?
2) Also rename to `.pickle`

Also, after I merge, I will run our unit tests. Any tests that should change?

**Comment by diyclassics** [comment]
> Also, after I merge, I will run our unit tests. Any tests that should change?

This is the addition of a new file, not referenced in the current code (but required by a coming PR), so it shouldn't effect current testing.

**Comment by kylepjohnson** [comment]
OK just rename it, please, and I'll merge.

**Comment by diyclassics** [comment]
```
# Imports
import os.path
import pickle
from cltk.utils.utils import CLTK_DATA_DIR
from pprint import pprint

# Define classifier
classifier_path = os.path.normpath(
    os.path.join(CLTK_DATA_DIR, "lat/model/lat_models_cltk/tokenizers")
    )

classifier = pickle.load(open(os.path.join(classifier_path, 'lat_enclitic_splitter.pickle'), 'rb'))

def lat_enclitic_features(word: str) -> dict:
    """
    Define features for classification
    """
    def stem(word):
        if word.endswith('que'):
            return word[:-3]
        else:
            return word[:-2]
    return {
            'last_6_letters': word[-6:],
            'last_7_letters': word[-7:],
            'last_8_letters': word[-8:],
            'stem_last_3_letters': stem(word)[-3:],
            'length_gt_7': len(word) > 7,
           }

print(classifier.classify(lat_enclitic_features('quoque'))) # 0, i.e. do not split
print(classifier.classify(lat_enclitic_features('nihilne'))) # 1, i.e. split
```

**Review by kylepjohnson — APPROVED** [review]

**Pull request merged**
